logging:
  level:
    org.hibernate.sql : debug

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB