name: Build and Push to ECR

on:
  push:
    branches:
      - jaebin

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # 1. 리포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. AWS 환경 변수 설정
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_PRIVATE_KEY }}
          aws-region: ap-northeast-2

      # 3. AWS ECR 로그인
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Docker 이미지 빌드 및 ECR 태그 설정
      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}
          DOCKER_BUILDKIT=1 docker build --platform linux/amd64 \
            -t 891377255417.dkr.ecr.ap-northeast-2.amazonaws.com/mozip-user:$TAG .

      # 5. ECR에 Docker 이미지 푸시
      - name: Push to Amazon ECR
        run: |
          TAG=${{ github.sha }}
          docker push 891377255417.dkr.ecr.ap-northeast-2.amazonaws.com/mozip-user:$TAG

      # 6. SSH 설정
      - name: Setup SSH key for accessing IaC repo
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_IAC }}

      # 7. GitHub 사용자 설정
      - name: Set Git config
        run: |
          git config --global user.name "jaebinGit"
          git config --global user.email "tnwoql327@gmail.com"

      # 8. IaC Private Repo에 이미지 태그 업데이트 (Argo CD 자동 배포)
      - name: Clone IaC Repo and Update Tag
        run: |
          TAG=${{ github.sha }}
          git clone git@github.com:jaebinGit/hachwimu-iac-jaebin.git
          cd hachwimu-iac-jaebin
          sed -i "s|image: .*mozip-user:.*$|image: 891377255417.dkr.ecr.ap-northeast-2.amazonaws.com/mozip-user:${TAG}|g" rollout.yaml

          git add rollout.yaml
          git commit -m "Update user image to ${TAG}" || echo "Nothing to commit"
          git push origin main || echo "Push failed"

      #test
